sudo: false
language: python
python:
  - "2.7"

install:
  - "pip install -r requirements/test.txt"
  - "pip install -q python-coveralls"
  - "python setup.py install"
  
# command to run tests
script: nosetests

after_success:
  - coveralls
